//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosBooking
    {
        public int ID { get; set; }
        public Nullable<int> ComplaintID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual hosComplaint hosComplaint { get; set; }
        public virtual hosRoom hosRoom { get; set; }
    }
}
