//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosComplaint
    {
        public hosComplaint()
        {
            this.hosBookings = new HashSet<hosBooking>();
            this.hosComplaintExaminations = new HashSet<hosComplaintExamination>();
            this.hosDiagnosis = new HashSet<hosDiagnosi>();
            this.hosPrescriptions = new HashSet<hosPrescription>();
            this.hosTransactions = new HashSet<hosTransaction>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<hosBooking> hosBookings { get; set; }
        public virtual ICollection<hosComplaintExamination> hosComplaintExaminations { get; set; }
        public virtual hosDoctor hosDoctor { get; set; }
        public virtual hosPatient hosPatient { get; set; }
        public virtual ICollection<hosDiagnosi> hosDiagnosis { get; set; }
        public virtual ICollection<hosPrescription> hosPrescriptions { get; set; }
        public virtual ICollection<hosTransaction> hosTransactions { get; set; }
    }
}
