//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosDiagnosi
    {
        public int ID { get; set; }
        public Nullable<int> ComplaintID { get; set; }
        public Nullable<int> DiseaseID { get; set; }
        public string Comment { get; set; }
    
        public virtual hosComplaint hosComplaint { get; set; }
        public virtual hosDisease hosDisease { get; set; }
    }
}
