//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosDisease
    {
        public hosDisease()
        {
            this.hosDiagnosis = new HashSet<hosDiagnosi>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<hosDiagnosi> hosDiagnosis { get; set; }
    }
}
