//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosInsurance
    {
        public hosInsurance()
        {
            this.hosPatients = new HashSet<hosPatient>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual ICollection<hosPatient> hosPatients { get; set; }
    }
}
