//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosPatient
    {
        public hosPatient()
        {
            this.hosComplaints = new HashSet<hosComplaint>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> InsuranceID { get; set; }
    
        public virtual ICollection<hosComplaint> hosComplaints { get; set; }
        public virtual hosInsurance hosInsurance { get; set; }
        public virtual hosUser hosUser { get; set; }
    }
}
