//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosRoom
    {
        public hosRoom()
        {
            this.hosBookings = new HashSet<hosBooking>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<hosBooking> hosBookings { get; set; }
    }
}
