//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hosUser
    {
        public hosUser()
        {
            this.hosDoctors = new HashSet<hosDoctor>();
            this.hosPatients = new HashSet<hosPatient>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Online { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
    
        public virtual ICollection<hosDoctor> hosDoctors { get; set; }
        public virtual ICollection<hosPatient> hosPatients { get; set; }
    }
}
