//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Management.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hosBooking> hosBookings { get; set; }
        public virtual DbSet<hosComplaint> hosComplaints { get; set; }
        public virtual DbSet<hosComplaintExamination> hosComplaintExaminations { get; set; }
        public virtual DbSet<hosDiagnosi> hosDiagnosis { get; set; }
        public virtual DbSet<hosDisease> hosDiseases { get; set; }
        public virtual DbSet<hosDoctor> hosDoctors { get; set; }
        public virtual DbSet<hosExamination> hosExaminations { get; set; }
        public virtual DbSet<hosInsurance> hosInsurances { get; set; }
        public virtual DbSet<hosMedication> hosMedications { get; set; }
        public virtual DbSet<hosPatient> hosPatients { get; set; }
        public virtual DbSet<hosPrescription> hosPrescriptions { get; set; }
        public virtual DbSet<hosRoom> hosRooms { get; set; }
        public virtual DbSet<hosTransaction> hosTransactions { get; set; }
        public virtual DbSet<hosUser> hosUsers { get; set; }
    }
}
